name: GraphQL Server Tests

on:
    push:
        paths:
            - 'server/**'
    pull_request:
        paths:
            - 'server/**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies for GraphQL server
              run: pnpm ci
              working-directory: ./server

            - name: Test GraphQL server
              run: pnpm test
              working-directory: ./server
