name: Next.js Tests

on:
    push:
        paths:
            - 'app/**'
    pull_request:
        paths:
            - 'app/**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 8.0.0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'

            - name: Install dependencies for Next.js app
              run: cd app && pnpm ci

            - name: Test Next.js app
              run: cd app && pnpm test
